### ISSUE TITLE
Sorting issue with new new state progress bar

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#10]
1. Select organization 
2. Select project
3. Select languages
4. Sort by progress
5. Compare Spanish with Turkish 
6. It does not fit. Works with older version.

**Comment by rakekniven** [comment]
Reported beginning of august. See https://twitter.com/transifex/status/894685156769792000

**Comment by samuelchan22** [comment]
This might have to do with your screen size. Could you confirm if this is still an issue?

We've updated the resources/languages pages with a sorting option for completion, which sorts the list by most reviewed first, then most translated second.

**Comment by rakekniven** [comment]
You are right. View is now different and works like you describe.
