### ISSUE TITLE
Allow to send messages to more than one person 

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#11]
Sometimes you need to discuss things with more than one person e.g. Adding new languages to a project.

Currently your possibility is a one-to-one conversation.

At the moment you have to use other channels like email, irc or forums.

**Comment by comradekingu** [comment]
The messaging platform is broken, don't use it.

**Comment by rakekniven** [comment]
@comradekingu See https://github.com/rakekniven/Transifex-Issues/issues/3#issuecomment-336647483

**Comment by rakekniven** [comment]
Closing here. For any further discussions please visit https://community.transifex.com/
