### ISSUE TITLE
Please offer an open forum or something similar to get in contact with OSS people

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#13]
Offering an email address (support@transifex.com) is not enough.
OSS people have ideas, want to discuss with you to improve your service.

Already addressed: https://twitter.com/rakekniven/status/894662476826062849

Having an open forum / issue tracker will make this repository superfluous.

**Comment by samuelchan22** [comment]
We've discussed this a bit internally and we definitely want a better channel to connect with the OSS community. At this point, we don't have the resources (people) to manage this well, so we'll look to revisit this topic in 2018. For now, I'd say continue creating issues here and we'll keep an eye on them.

**Comment by rakekniven** [comment]
Works for me at the moment.

**Comment by comradekingu** [comment]
Transifex has been the same since 2013, and didn't interact with the free software community when it had a free software license. Don't waste your time. The Pootle and Weblate devs respond right away.

**Comment by rakekniven** [comment]
@comradekingu https://github.com/rakekniven/Transifex-Issues/issues/3#issuecomment-336647483 If you do not stop, I will delete your comments here.

**Comment by comradekingu** [comment]
The reason why the open source/free software model doesn't work, is because Transifex isn't free software. As a direct result thereof, they are at the leisure of not listening, and not doing anything about it. While it could have been different, it isn't, which makes sense considering the amount of bugs on the platform. Do what you want with my comments, or [the comments of others](https://www.transifex.com/nextcloud/teams/64236/discussions/18034/). My only intention is for you not to waste your time on counterproductive charity.
Eventually you will find, as I and everyone else has, that Transifex will not change.

**Comment by rakekniven** [comment]
Hello @samuelchan22 It is 2018 already and I want to come back to you.
Any news from your side?

**Comment by samuelchan22** [comment]
@rakekniven Thanks for checking in. We've been discussing it some more internally and have some ideas, but they're still in the early stages. It'll probably be a little while longer before we have this, as our team is small and have limited capacity.

**Comment by rakekniven** [comment]
Hello @samuelchan22 Hope you see the value you are getting by reported bugs and idea for improvements (do not talk about big new features).

**Comment by samuelchan22** [comment]
@rakekniven We absolutely do! :) It's just going to take time to do it right, designing it, moderating it, etc.

**Comment by glezos** [comment]
A quick update on this — we are, indeed, making progress on this and working on a website for our community. :)

**Comment by rakekniven** [comment]
Hello @glezos , could you show or explain the way you will interact with the community in the future?

**Comment by rakekniven** [comment]
We can close this one.

See https://community.transifex.com/t/welcome-to-the-transifex-community-portal/8

**Comment by txgittest** [comment]
As @rakekniven mentioned, Transifex Community is available to all users! We would love to have all you contributing and posting about your workflow and experience in Transifex! 
We look forward to seeing you there!
Best,
Flavia
Customer Success Manager at Transifex
