### ISSUE TITLE
No way to be warned when new strings have to be translated

### ISSUE THREAD

**Issue by ldmpub** [rakekniven/Transifex-Issues#14]
No mail received neither when a new key has been added (translation to be done) nor when a new suggestion has been added (to be reviewed) nor when a translation has been approved / revised (to get coordinator agreement).

**Comment by rakekniven** [comment]
You can get notfications about new content to translate.

No notification about strings to review.

**Comment by ldmpub** [comment]
In my profil, under notification section, all options are ticked.
Did I miss a setting somewhere else? in the project?

**Comment by rakekniven** [comment]
Hello @ldmpub ,

see next two pictures of my secons. See small icon on second one. Their I "watched" the whole project.

<img width="597" alt="bildschirmfoto 2017-10-01 um 18 57 14" src="https://user-images.githubusercontent.com/2069590/31133638-663172e0-a860-11e7-837c-70119a79c072.png">

<img width="877" alt="bildschirmfoto 2017-10-01 um 18 57 54" src="https://user-images.githubusercontent.com/2069590/31133645-6bb55556-a860-11e7-9037-497644d272ac.png">

**Comment by ldmpub** [comment]
Hi,

Thanks for this info. I have subscribed to the whole Nextcloud project.
Now each day I receive a useless email like today:

> "Hi Ldm Public, 
> 
> 69 files in the project Nextcloud were updated with new content."

followed by 69 links to "sub-ressources".

Neither in th email nor by clicking on each of the 69 links I can find any changes list nor any activity report to know what changes have been done and what I have to do as a translator to improve project translation ;-(.

**Comment by rakekniven** [comment]
And yes, you are right. That email is nearly useless. It just says, that transifex robot successfully interacted with GitHub repositories.

[QOwnNotes](http://www.qownnotes.org/) is using Crowdin as translation platform. Their daily mails are in detail. Have no one at the moment. Will append one later.

**Comment by ldmpub** [comment]
100% agree: this daily mail is for admins (not for translators nor coordinators).

It's a kind of "system monitoring mail" useless for translator because: it's not linked to the real activity for their language strings and there are no info at all on what they have to do to improve the translation (already pointed out in my above post).

**Comment by rakekniven** [comment]
Example from Crowdin:
![grafik](https://user-images.githubusercontent.com/2069590/31457447-0e8a6ba6-aebd-11e7-85af-d794282909bb.png)

@samuelchan22 What do you think?

**Comment by samuelchan22** [comment]
@rakekniven Thanks for sharing. What happens when you click on the "Translations" link in the email above? And to help me better understand, is the "XX number of files have been updated" email not useful because it's not clear which file needs to be worked on (first)?

**Comment by ldmpub** [comment]
Right! What misses in the current email from Transifex are the following details with relevant url links to start the work in Transifex...

In first priority:
- new strings => to be translated
- strings modified in the source => to be reviewed = does translation need to be changed?

In second priority:
- new resource file added => to be translated
- new suggestions => to be accepted / refused.

It's not only the mail content but also Transifex "translation process" which is concerned.

**Comment by comradekingu** [comment]
It broke for Nextcloud recently, but will still give you updates. It is broken in different ways depending on the project, so just click the eye and hope for the best.

**Comment by ldmpub** [comment]
Thanks for your feedback.

Note: the content of this notification should also be localized based on the recipient / translator preferred language.

**Comment by rakekniven** [comment]
Closing here. For any further discussions please visit https://community.transifex.com/
