### ISSUE TITLE
No way to search in translation history

### ISSUE THREAD

**Issue by ldmpub** [rakekniven/Transifex-Issues#15]
I want to find old strings in the case I'm running an old app version, to check how translation has evolved in the new app (search the old translation and display now the new translation).

**Comment by rakekniven** [comment]
You can see history of each string?

**Comment by ldmpub** [comment]
Yes I can browse all strings one by one and look at their history ... but I need a whole search feature in "old strings".

Note: this is an existing use case but I agree it has a low priority (compared to my other "issues").

**Comment by rakekniven** [comment]
Closing here. For any further discussions please visit https://community.transifex.com/
