### ISSUE TITLE
No way to remove warnings

### ISSUE THREAD

**Issue by ldmpub** [rakekniven/Transifex-Issues#16]
Transifex adds automatic warnings on translations (orange triangle before line in main view).

For instance when the translation contains a word "out of the glossary", there is a warning ... but it's impossible even as a coordinator to remove these warnings => making this feature unusable because "too much information kills information" ;-(.

At least we need the following actions on translations "Ignore this warning / ignore all warnings".

**Comment by samuelchan22** [comment]
Would you be able to help us understand the use case where you'd want the warning message to be disabled? 

Btw, these translation checks can be customized by Admins: https://docs.transifex.com/setup/setting-translation-checks.

**Comment by ldmpub** [comment]
Hi, as far as I know I'm not an admin but just a "power" user / translator.

Attach is a screen copy of 1 use case
![warnings](https://user-images.githubusercontent.com/1452146/31199000-64031414-a956-11e7-8d6e-ec83ddcd026c.png)

What do you suggest to handle this warning? I have added a 2d translation for the word settings without any success on removing this warning.

Note: if a warning is always shown, other warning will become less and less used because it's a king of "false positive".

**Comment by rakekniven** [comment]
AFAIK glossary is case sensitive. Just played arround a little and in german it is not very useful.
Will provide example later today.

**Comment by comradekingu** [comment]
This feature is broken. Don't put anything in the dictionary.

**Comment by rakekniven** [comment]
@ldmpub Any news from your side? Have you tried case sensitive entries?

**Comment by ldmpub** [comment]
These unrelevant warnings are still annoying and can not be removed, see an other example below taken today:
![still annoying](https://user-images.githubusercontent.com/1452146/39088592-107ee966-45b5-11e8-8c64-bbd9edf31726.jpg)
plurial should apply in french and is not "recognized" raising an unwanted warning ;-(.

**Comment by rakekniven** [comment]
@samuelchan22 This looks like a bug, or?

**Comment by samuelchan22** [comment]
@rakekniven Case sensitivity might be a feature, I'm not sure. But in the case of this last screenshot, could you help me understand the issue? It seems the translation used a plural version (dossiers) when the source was singular (folder), hence the warning.

**Comment by rakekniven** [comment]
@ldmpub Could you explain your screenshot?

**Comment by ldmpub** [comment]
Hi, you are right => I removed the S to "Dossiers" and get rid of the annoying warning.

Then, questions are:
- at application level, are we really speaking of "only "one" folder"? => none of us can say (I should ask ownCloud project Team!)
- is transifex able to detect (un)consistency between source and target strings, here able to block or allow plural difference in 2 languages?

Thanks for your answer,

**Comment by samuelchan22** [comment]
To just speak to the Transifex side of things, the behavior of the translation check can be customized the Organization Admin. By default, a warning is displayed when a translation is missing a translation present in the glossary. This lets you save the translation but you'll see the warning (which is what you experienced). Currently, our glossary doesn't let you note if a glossary term is singular or plural.

**Comment by rakekniven** [comment]
Closing here. For any further discussions please visit https://community.transifex.com/
