### ISSUE TITLE
Search bar entries are not translated

### ISSUE THREAD

**Issue by ldmpub** [rakekniven/Transifex-Issues#17]
The search bar is not translated at all (at least in french) making search really very difficult to use.
For instance how can a regular user understand difference between "Text" and "Translation Text" which are the 2 first criterias of this search bar!?

For a translation tool it's a shame to have part of its UI not translated in one of the world's major language!

**Comment by rakekniven** [comment]
Is your user interface available in french?
Just checked my user profile and cannot select any language.

**Comment by rakekniven** [comment]
Just discovered settings at bottom right. No german :-(

<img width="241" alt="bildschirmfoto 2017-09-30 um 15 42 36" src="https://user-images.githubusercontent.com/2069590/31046264-077e10f8-a5f6-11e7-9e38-33e0533fda1b.png">

**Comment by ldmpub** [comment]
You're right: setting language is well hidden in profil ;-( and only few languages are available ;-((.

By the way my original claim was:  even when UI is set to french the search bar uses english vocabulary!

**Comment by rakekniven** [comment]
Yes, understood. 

Another thought (workaround): If source language is english, the translator should be able to handle this.

**Comment by samuelchan22** [comment]
Translations for Transifex's UI are crowdsourced [1]. And unfortunately, German is currently less than 50% translated, so we cannot make it available as an option yet. If anyone would like to contribute translations, we won't be opposed ;) 

[1] https://www.transifex.com/transifex/transifex/core/

**Comment by rakekniven** [comment]
Hello @samuelchan22 Thank you for joining us.

Regarding the user's question: Is the search bar translatable?

**Comment by samuelchan22** [comment]
Hmm you're right, that's odd. We'll have to look into this and get back to you.

**Comment by ldmpub** [comment]
Request to join core Transifex translation team done!

**Comment by samuelchan22** [comment]
@ldmpub Request approved, thanks!

**Comment by rakekniven** [comment]
I would join as well. Good compensation would be to answer other issues here. What do you think?

**Comment by ldmpub** [comment]
Can you please change my rights / Yet I can not change any reviewed translation:
- neither submit a request for change (with my proposal)
- not "unrevised" a string.
See for instance my suggestion here: https://www.transifex.com/transifex/transifex/translate/#fr_FR/core/113846783?qt=La%20traduction%20du%20glossaire%20pour%20le%20mot

**Comment by samuelchan22** [comment]
@ldmpub I've made you a reviewer for French.

@rakekniven I'm still looking into some of the issues and checking on their status with some teammates. To be frank, there are a lot of issues and we won't be able to solve all of them in the near term.

**Comment by ldmpub** [comment]
Thanks, from the new reviewer ;-).

**Comment by rakekniven** [comment]
@samuelchan22 I value your input. Some of the issues are minor, some are really important when managing bigger community projects.

**Comment by samuelchan22** [comment]
@rakekniven Thanks for understanding. Regarding this issue, we're going to update how the filters work in the Editor. As part of this update, we'll make the filters translatable (they're currently not part of the Core.po resource unfortunately).

**Comment by comradekingu** [comment]
@ldmpub You can help translate [Pootle](https://pootle.locamotion.org/projects/pootle/) and [Weblate](https://hosted.weblate.org/projects/weblate/master/). The French translation is completed for Weblate, but there might be room for improvement. Pootle is not yet done, so you could make a lot of impact there. LibreOffice uses it for example.
Transifex is not free software(!)

**Comment by ldmpub** [comment]
@comradekingu I'm personally the french translator behind Weblate (using the same ldmpub account) ... that's the reason why this translation is completed ;-). I do not use Pootle at all, yet. Transifex is not a free software? That's not a problem it just need to be a good piece of software with good translations powered by a team open to improvments.

**Comment by comradekingu** [comment]
@ldmpub Even if that was true of Transifex, it still wouldn't be anywhere close to equivalent. You cant use it as you please, see the sourcecode, change or distribute it.
Case in point, look at the disparity to the development model of Nextcloud, or their motives, it has all of those, and more.
What is worse, the only people that can do anything about Transifex being broken, are doing nothing.
elementaryOS recently changed to Weblate, not even hosted Weblate at that, their own instance, meaning essentially nobody has an account right thereafter.
It resulted in over 100000 errors picked up, the great majority of which are true positives. Activity was up greatly, not even a week after the switch.
Tell me that is irrelevant and I will show you a result that has improved far beyond what one could have hoped to have changed with it being on Transifex.

**Comment by samuelchan22** [comment]
@ldmpub We just released an update to the Search Filter UI in the Editor today. Everything should be translatable now! Closing this issue.

**Comment by rakekniven** [comment]
@samuelchan22 Applied some days ago to translate Transifex but still no response.

Found a bug regarding the new search bar. Report it here?
