### ISSUE TITLE
Unable to use copy / paste with keyboard shortcuts

### ISSUE THREAD

**Issue by ldmpub** [rakekniven/Transifex-Issues#18]
It's impossible to make Ctrl C / Ctrl + V work in the "translation zone"!

**Comment by rakekniven** [comment]
Which OS? Browser?

Using it very often with Firefox on OS X and windows. Works pretty well.

**Comment by ldmpub** [comment]
Firefox under Windows 10.

To reproduce:
- when performing translation, click on little "thunder" (ie automatic translation)
- need to move one word at the beginning to, for instance, the end of sentence: 
 . Ctrl + C / cut: it's OK => selected words are remove and clipboard content is ok
 . Ctrl + V / paste: no effect

Note: with right-click and contextual menu copy/paste are working but it's counterproductive ;-(.

**Comment by ldmpub** [comment]
Copy / Paste keyboard shortcuts are working under Chrome + Ubuntu!

**Comment by rakekniven** [comment]
Are you having any add-ons installed in your Firefox e.g. Skriptblocker or similar?

**Comment by ldmpub** [comment]
I will have a deaper look. Thanks.

**Comment by comradekingu** [comment]
Very interesting, could you explain the whole use-case? What is it you are doing.

**Comment by rakekniven** [comment]
Closing this here. For any further discussions please visit https://community.transifex.com/
