### ISSUE TITLE
Allow import of of glossary

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#2]
Role: Project maintainer

Currently you can download existing glossary for one/all languages (notes as option) as csv file. 
That's great btw.

As a power user I would like to edit my glossary list externally and upload it.
So please make import/upload possible.

**Comment by samuelchan22** [comment]
Uploading a glossary is possible, though only Admins are able to do this for the time being. Instructions can be found here: https://docs.transifex.com/setup/glossary/uploading-an-existing-glossary

**Comment by rakekniven** [comment]
As an project maintainer I am able to edit and download glossary.
Doesn't it make sense to allow import as well?

**Comment by samuelchan22** [comment]
I see what you're saying and we'll have to discuss this some more internally. Organizations typically share a single glossary across multiple projects, so by allowing import from a single project and bulk changes to the glossary, it could potentially impact other projects as well, which the maintainer shouldn't be able to do.

**Comment by rakekniven** [comment]
Ok, seeing your argument makes sense.
You can close issue.

**Comment by samuelchan22** [comment]
It doesn't seem like I have the ability to close the issue. Would you be able to mark it as closed?
