### ISSUE TITLE
Usability: People requesting languages instead of joining already existing languages. 

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#20]
Nextcloud project:
90% of the requests are duplicates.

1.   User is requesting e.g. French (fr_FR) then discovers there is French already (FR). The user joins existing French team and I have to decline the request
2.   User is requesting e.g. French (fr_FR) and does NOT discover there is French already (FR). I sent a message to the user and pointing him to the French team and decline the request.

So I wonder why there are so many "bad" requests? IMHO Transifex should check the process/workflow/usability of requesting languages.

Related with #12

**Comment by mikegianno** [comment]
Hi @rakekniven ,

We have enhanced the request language modal to display the existing languages as well.
So now if someone wants to request French and starts typing, existing languages will also be displayed as inactive with an "Already exists" helptext.

**Comment by rakekniven** [comment]
Hello @mikegianno,

Ok, let's close this for now and I will come back if necessary.

**Comment by rakekniven** [comment]
Hey @mikegianno ,

please see https://community.transifex.com/t/usability-people-requesting-languages-instead-of-joining-already-existing-languages/2124
