### ISSUE TITLE
Link to overall project issues does not forward to strings with issues

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#21]
Before Transifex introduced the new search bar it works like expected.

Current state:
Open project. See total issue counter. Here 19 issues.

<img width="1028" alt="bildschirmfoto 2018-04-21 um 15 34 01" src="https://user-images.githubusercontent.com/2069590/39085192-6d1b5fe6-457f-11e8-8379-81e47d9c0db2.png">

Click at it and you are forwarded to list without any filter:

<img width="747" alt="bildschirmfoto 2018-04-21 um 15 35 28" src="https://user-images.githubusercontent.com/2069590/39085194-6f58adae-457f-11e8-879d-88036015e12c.png">

What should be shown is:

<img width="745" alt="bildschirmfoto 2018-04-21 um 15 35 55" src="https://user-images.githubusercontent.com/2069590/39085195-7113c980-457f-11e8-917c-2c957c0e6489.png">

**Comment by rakekniven** [comment]
@samuelchan22 One more bug.

**Comment by samuelchan22** [comment]
@rakekniven We have a fix in place for this already — it's just waiting to be deployed.

**Comment by rakekniven** [comment]
So, the wait is over, please deploy :-)

**Comment by samuelchan22** [comment]
@rakekniven It should be fixed now, could you confirm?

**Comment by rakekniven** [comment]
Yes, it works like expected.

**Comment by rakekniven** [comment]
Reopen this. Worked for some weeks.
Now the argument for issues is not yes/no anymore.

@samuelchan22  See screenshot.

<img width="577" alt="bildschirmfoto 2018-05-21 um 17 29 04" src="https://user-images.githubusercontent.com/2069590/40317970-61e649d6-5d23-11e8-834e-73b1381d590a.png">

**Comment by samuelchan22** [comment]
@rakekniven We have a fix and will be deploying it later this week.

**Comment by samuelchan22** [comment]
The fix has been deployed.
