### ISSUE TITLE
Statistics overlay is in the way while language switching

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#22]
Hello,

I am often switching languages while working on maintaining things.
When moving cursor up to language selection box I have to cross progress bar and a small statistic information box comes up.
This is in the way of the box and I have to move cursor away and back to the box.

![2018-08-30_07h28_15](https://user-images.githubusercontent.com/2069590/44894644-1f7a3a80-acf1-11e8-9636-40c39baf93b0.png)

@samuelchan22

**Comment by mikegianno** [comment]
Hi @rakekniven thanks for pointing that out.

I work on Transifex and will be looking at these issues.

We will iterate on your feedback and get back to you, seems like a usability issue.

**Comment by mikegianno** [comment]
Hi again @rakekniven ,

This issue should be fixed now. Could you please validate?

**Comment by rakekniven** [comment]
Yes, way better now. If you move the mouse cursor slowly up it happens again, but you really have to be slow.

Thx for your feedback.
