### ISSUE TITLE
Sort resource list in daily notification email 

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#3]
Everyday team members get a nice notification email from Transifex.
It tells us a total number of updated resources and adds a list of them.

That list is not sorted as expected.

It should be sorted alphabetically.

Reason for request:
Some translators are just translating one resource. They need to grep daily email for their resource and and alphabetic sorting helps them and make it more clear.

**Comment by rakekniven** [comment]
Already reported via email to Transifex in 2016.
Response came from a lady and it says "will put it on agenda".
Unfortunately I cannot find that email.

@samuelchan22 Any update on here?

**Comment by samuelchan22** [comment]
@rakekniven No updates yet, but it should be something we can change.

**Comment by comradekingu** [comment]
Please don't make them touch the notification system. It is riddled with bugs, and I rely on it to keep on top of things, which is next to impossible on Transifex.

**Comment by rakekniven** [comment]
@comradekingu Please stop commenting that way. I created this repo to get in contact with Transifex. In a constructive way. Nextcloud is currently not using Pootle or similar Open Source tools. It is using Transifex. See [README.md](https://github.com/rakekniven/Transifex-Issues/blob/master/README.md) . This is a warning.

**Comment by rakekniven** [comment]
@samuelchan22 Looks like you changed something to solve issue? Can you confirm?

Send you invitation to this repo some time ago. Please accept it and your are able to close issues as well. Thank you.

**Comment by samuelchan22** [comment]
@rakekniven Hmm I don't believe so, let me check and get back to you. And thanks for the invite, just joined!

**Comment by samuelchan22** [comment]
@rakekniven Confirmed this has been fixed — we're now sorting things alphabetically where applicable. Thanks for the suggestion!
