### ISSUE TITLE
Add function to compare two languages inside web UI

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#5]
Example: German has two language forms. See Nextcloud project.
One language is formel an the other one is informel.
Differences are not that big, but there are some of them. I would say 98% off all strings are the same.

Transifex does not support this case. You cannot compare two resources of two languages within web UI.

Same should apply for e.g. Chinese languages.

**Comment by samuelchan22** [comment]
I'm not sure I understand the issue completely. You'd like to compare the translations of two similar languages?

**Comment by rakekniven** [comment]
Yes, I like to compare two languages without downloading resource files manually. Updated my first post.

**Comment by samuelchan22** [comment]
Does this feature achieve what you're looking for? You can't compare two different resources, but you can compare two languages within the same resource.

View source strings in a different language: https://docs.transifex.com/translation/tools-in-the-editor#view-source-strings-in-a-different-language

**Comment by comradekingu** [comment]
This is broken far beyond comparison, not going to happen.
