### ISSUE TITLE
Option to accept languages is visible for translators - should not be

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#7]
On iOS I have seen the option to accept/deny languages without rights.

When tapping actions screen shows dialog for short time.
Than it disappears.

Project: Nextcloud
Username: rakekniven

**Comment by rakekniven** [comment]
Could not reproduce it after having role of project maintainer.

Anyone else?

**Comment by comradekingu** [comment]
I don't think there are any open requests now.

**Comment by rakekniven** [comment]
Just make one and try it on iOS.

**Comment by rakekniven** [comment]
Closed. Not reproduceable.
