### ISSUE TITLE
Combine users inbox and outbox to have a threaded view of messages

### ISSUE THREAD

**Issue by rakekniven** [rakekniven/Transifex-Issues#8]
Currently there are separated folders for inbox and sent messages.

Please overwork view and show threaded conversations.

That helps a lot while communicating.

**Comment by comradekingu** [comment]
So many people that use Transifex heavily has been saying this for years and years. The messaging system is severely broken beyond this.

**Comment by rakekniven** [comment]
@samuelchan22 Anything on your roadmap regarding this issue?

**Comment by samuelchan22** [comment]
@rakekniven Not currently, but I'll push for it for to be included in the 2018 roadmap. We're aware there's room to improve our messaging and announcement/discussions features.

**Comment by rakekniven** [comment]
Reported at https://community.transifex.com/t/combine-users-inbox-and-outbox-to-have-a-threaded-view-of-messages/185

**Comment by rakekniven** [comment]
Closing this and will continue to discuss at transifex community.
